sudo: true
dist: xenial
language: minimal
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
branches:
  only:
    - master
deploy:
  - provider: script
    script: bash deploy.sh
    on:
      branch: master
